### ISSUE TITLE
Game crashes to desktop

### ISSUE THREAD

**Issue by krumble1** [elytra/Unclouded#1]
https://pastebin.com/fnveCFvU

I also had tabbed out of the game while waiting, if that makes a difference.

**Comment by exaskye** [comment]
Seems like a mod is adding or removing a resource listener *in* a resource listener.

**Comment by krumble1** [comment]
This time it crashed for no obvious reason. Was sort of exploring, so maybe worldgen? I'm grasping at straws; you guys are the pros.

https://pastebin.com/gwsKsM3h

**Comment by krumble1** [comment]
Just wanted to clarify, I more or less expect crashes, so I'm not complaining. :) I just want to be as helpful as I can.

**Comment by krumble1** [comment]
Interesting. Just crashed again by going to the same coordinates.
https://pastebin.com/KEED3h6r

Edit: I'm just going to keep adding them to this comment instead of making new ones.

- Crash to desktop with no obvious causes: https://pastebin.com/2sekWYDf
- Crashed to desktop with no obvious causes: https://pastebin.com/aZjr7HT1
        - Shortly after this one I pointed at the same block and crashed again: https://pastebin.com/AuDNiKKr
        - And again on the same block: https://pastebin.com/AuXuevae
        - Here's a potato recording with my phone of this happening: https://vid.me/nEYTr

I'm starting to see a trend here. Most, if not all, of my crashes seem to be triggered by pointing at certain "unstable" blocks or something. I don't think I'm running out of memory but I'm going to try allocating less to the game to make sure that's not the problem. (Just tried it - that doesn't seem to help.)J

- New location, another crash: https://pastebin.com/dMyUW5td
        - Same location: https://pastebin.com/uRMi7RN9

- New location: https://pastebin.com/z6rAGPqG
        - Facing towards the same block more or less, but on a different Y axis and slightly different X and Z axes: https://pastebin.com/YaYg2kqW
        - Same X, Y, Z axes but looking level instead of up at an angle: https://pastebin.com/gVnFDCry

**Comment by BBoldt** [comment]
Almost *all* of those crashes refrence Waila. Issue is i'm not sure it's a waila or a fruitphone crash, as they both use the same things I think.

**Comment by BBoldt** [comment]
Also, the first crash you posted is not related to all the other ones, but all the other ones seem to be related to eachother.

**Comment by exaskye** [comment]
DecoratorRenderer suggests Waila is enabled and is not being funneled through Fruit Phone.
