### ISSUE TITLE
Charset block carrying doesn't work on Bibliocraft shelves

### ISSUE THREAD

**Issue by krumble1** [elytra/Unclouded#4]
Tested with "Oak Shelf" and "Acacia Shelf" from _Bibliocraft_.

**Comment by krumble1** [comment]
Also doesn't seem to work on _Tinkers' Construct_ "Crafting Station"

**Comment by BBoldt** [comment]
I don't think its meant to work on everything.

@asiekierka What are the conditions for carrying things?

**Comment by asiekierka** [comment]
Modded blocks with tile entities need to be whitelisted. See PackDevTips.

**Comment by exaskye** [comment]
Moving requests of this type to https://github.com/elytra/Unclouded/projects/4
