### ISSUE TITLE
Feature request: Renew invalid session

### ISSUE THREAD

**Issue by krumble1** [elytra/Unclouded#5]
I get [_Invalid session - try restarting client_](http://i.imgur.com/MKJnPpv.png) type of errors a lot because I have a friend who uses my account sometimes. Would it be possible to add a button in the main screen to "re sign in"? I have no idea how the authentication works so I'm shooting in the dark here.

**Comment by Shadows-of-Fire** [comment]
https://minecraft.curseforge.com/projects/reauth
