### ISSUE TITLE
pam's harvestcraft is nerfing vanilla food values.

### ISSUE THREAD

**Issue by jonqrandom** [elytra/Unclouded#8]
this is a recent(ish) change on the dev's part, is it supposed to be left turned on in the pack?

**Comment by LemmaEOF** [comment]
Yes, it's supposed to be left on. PHC toast is so OP anyway it's pretty much moot, honestly.

**Comment by exaskye** [comment]
I'm still not sure how I feel about the nerfed food values - leaning toward "in favor", which is why it's still on.

**Comment by exaskye** [comment]
Disabled due to it breaking garden cloches.
